#!/bin/sh

#git rm --cache  _site/2012/11/oracle-proc-segment-fault.html


 git rm --cache  _site/2013/03/bank-c-oracle.html
 git rm --cache  _site/2013/03/hack-bank.html
 git rm --cache  _site/2014/09/redis-mysql.html
 git rm --cache  _site/2014/10/SOA-dubbo.html
 git rm --cache  _site/2014/10/jstorm.html
 git rm --cache  _site/2015/02/java-with-JPA.html
 git rm --cache  _site/2015/04/dubbo-netty.html
 git rm --cache  _site/2015/06/redis-mysql-update-cache.html
 git rm --cache  _site/2015/10/iOS-Android-RSA-AES.html
 git rm --cache  _site/2016/03/linux-managment-gitlab.html
 git rm --cache  _site/2016/04/teamwork-construction.html
 git rm --cache  _site/2016/10/github-jekyll.html
 git rm --cache  _site/Gemfile
 git rm --cache  _site/Gemfile.lock
 git rm --cache  _site/about.html
 git rm --cache  _site/archive.html
 git rm --cache  _site/css/bootstrap.min.css
 git rm --cache  _site/css/font-awesome/HELP-US-OUT.txt
 git rm --cache  _site/css/font-awesome/css/font-awesome.css
 git rm --cache  _site/css/font-awesome/css/font-awesome.min.css
 git rm --cache  _site/css/font-awesome/fonts/FontAwesome.otf
 git rm --cache  _site/css/font-awesome/fonts/fontawesome-webfont.eot
 git rm --cache  _site/css/font-awesome/fonts/fontawesome-webfont.svg
 git rm --cache  _site/css/font-awesome/fonts/fontawesome-webfont.ttf
 git rm --cache  _site/css/font-awesome/fonts/fontawesome-webfont.woff
 git rm --cache  _site/css/font-awesome/fonts/fontawesome-webfont.woff2
 git rm --cache  _site/css/font-awesome/less/animated.less
 git rm --cache  _site/css/font-awesome/less/bordered-pulled.less
 git rm --cache  _site/css/font-awesome/less/core.less
 git rm --cache  _site/css/font-awesome/less/fixed-width.less
 git rm --cache  _site/css/font-awesome/less/font-awesome.less
 git rm --cache  _site/css/font-awesome/less/icons.less
 git rm --cache  _site/css/font-awesome/less/larger.less
 git rm --cache  _site/css/font-awesome/less/list.less
 git rm --cache  _site/css/font-awesome/less/mixins.less
 git rm --cache  _site/css/font-awesome/less/path.less
 git rm --cache  _site/css/font-awesome/less/rotated-flipped.less
 git rm --cache  _site/css/font-awesome/less/stacked.less
 git rm --cache  _site/css/font-awesome/less/variables.less
 git rm --cache  _site/css/font-awesome/scss/font-awesome.scss
 git rm --cache  _site/css/pics/random-grey-variations.png
 git rm --cache  _site/css/pics/triangles.png
 git rm --cache  _site/css/syntax.css
 git rm --cache  _site/css/theme.css
 git rm --cache  _site/feed.xml
 git rm --cache  _site/hyacker.psd
 git rm --cache  _site/images/batWid1.png
 git rm --cache  _site/images/bkg.png
 git rm --cache  _site/images/blacktocat.png
 git rm --cache  _site/images/cc_by_88x31.png
 git rm --cache  _site/images/dark_matter.png
 git rm --cache  _site/index.html
 git rm --cache  _site/js/bootstrap.min.js
 git rm --cache  _site/js/d3.layout.cloud.js
 git rm --cache  _site/js/d3.min.js
 git rm --cache  _site/js/header.js
 git rm --cache  _site/js/jquery.min.js
 git rm --cache  _site/page2/index.html
 git rm --cache  _site/projects.html
 git rm --cache  _site/tag/AES/index.html
 git rm --cache  _site/tag/C/index.html
 git rm --cache  _site/tag/Gitlab/index.html
 git rm --cache  _site/tag/JPA/index.html
 git rm --cache  _site/tag/RSA/index.html
 git rm --cache  _site/tag/SOA/index.html
 git rm --cache  _site/tag/android/index.html
 git rm --cache  _site/tag/bank/index.html
 git rm --cache  _site/tag/dubbo/index.html
 git rm --cache  _site/tag/iOS/index.html
 git rm --cache  _site/tag/java/index.html
 git rm --cache  _site/tag/jekyll/index.html
 git rm --cache  _site/tag/jstorm/index.html
 git rm --cache  _site/tag/linux/index.html
 git rm --cache  _site/tag/mysql/index.html
 git rm --cache  _site/tag/netty/index.html
 git rm --cache  _site/tag/nosql/index.html
 git rm --cache  _site/tag/oracle/index.html
 git rm --cache  _site/tag/pro*c/index.html
 git rm --cache  _site/tag/redis/index.html
 git rm --cache  _site/tag/security/index.html
 git rm --cache  _site/tag/shell/index.html
 git rm --cache  _site/tag/storm/index.html
 git rm --cache  _site/tag/teamwork/index.html
 git rm --cache  _site/tags.html

